POST http://localhost:8880/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhcnphZEBnbWFpbC5jb20iLCJleHAiOjE3NTQ2NTgwNjcsInVzZXJJZCI6MH0.2i27lFnS_eCd1DNrtyY1YwEPnVOa8ZPP9MFh9_gDq_A

{
    "name": "Farzad | Dev Event",
    "description": "this is the most perfect event of all the time",
    "location": "USA",
    "dateTime": "2025-01-01T15:30:00.000Z"
}